import { Preset } from "../types/scroll";
import { DEFAULT_CONFIG } from "./defaults";

export const PRESETS: Preset[] = [
  {
    id: "minimal",
    name: "Minimal",
    description: "Crisp black typography on a clean bright background with relaxed motion.",
    category: "Essential",
    config: {
      ...DEFAULT_CONFIG,
      text: "THE DETAILS ARE NOT THE DETAILS. THEY MAKE THE DESIGN.",
      direction: "left",
      speed: 80,
      typography: {
        ...DEFAULT_CONFIG.typography,
        fontFamily: "Space Grotesk",
        fontSize: 56,
        fontWeight: 600,
        letterSpacing: 2,
        textTransform: "uppercase",
      },
      colors: {
        ...DEFAULT_CONFIG.colors,
        textColor: "#0f172a",
        colorMode: "solid",
      },
      background: {
        ...DEFAULT_CONFIG.background,
        type: "solid",
        color: "#f8fafc",
      },
      effects: {
        ...DEFAULT_CONFIG.effects,
        glow: false,
        outline: false,
        shadow: false,
      },
      canvas: {
        width: 1920,
        height: 400,
        aspectRatio: "custom",
        presetName: "Website Banner",
      },
    },
  },
  {
    id: "breaking-news",
    name: "Breaking News",
    description: "High-alert broadcast ticker with rapid horizontal movement and high contrast.",
    category: "Broadcast & Retro",
    config: {
      ...DEFAULT_CONFIG,
      text: "🚨 BREAKING NEWS: SCROLLFORGE REACHES 1.0 RELEASE — HIGH VELOCITY ANIMATED TYPOGRAPHY ENGINE DEPLOYED GLOBALLY",
      direction: "left",
      speed: 260,
      typography: {
        ...DEFAULT_CONFIG.typography,
        fontFamily: "Oswald",
        fontSize: 54,
        fontWeight: 700,
        letterSpacing: 3,
        textTransform: "uppercase",
      },
      colors: {
        ...DEFAULT_CONFIG.colors,
        textColor: "#ffffff",
        colorMode: "solid",
      },
      background: {
        ...DEFAULT_CONFIG.background,
        type: "solid",
        color: "#dc2626",
      },
      effects: {
        ...DEFAULT_CONFIG.effects,
        glow: false,
        shadow: true,
        shadowX: 0,
        shadowY: 2,
        shadowBlur: 8,
        shadowSpread: 0,
        shadowColor: "rgba(0,0,0,0.5)",
      },
      canvas: {
        width: 1920,
        height: 400,
        aspectRatio: "custom",
        presetName: "Website Banner",
      },
    },
  },
  {
    id: "neon",
    name: "Neon Nights",
    description: "Deep darkness illuminated by electric cyan and magenta luminescence.",
    category: "Bold & Neon",
    config: {
      ...DEFAULT_CONFIG,
      text: "NEON DREAMS // ELECTRIC MOTION // FUTURE VISION",
      direction: "left",
      speed: 130,
      typography: {
        ...DEFAULT_CONFIG.typography,
        fontFamily: "Anton",
        fontSize: 72,
        fontWeight: 400,
        letterSpacing: 4,
        textTransform: "uppercase",
      },
      colors: {
        ...DEFAULT_CONFIG.colors,
        textColor: "#22d3ee",
        colorMode: "solid",
      },
      background: {
        ...DEFAULT_CONFIG.background,
        type: "solid",
        color: "#05060b",
      },
      effects: {
        ...DEFAULT_CONFIG.effects,
        glow: true,
        glowColor: "#06b6d4",
        glowIntensity: 6,
        glowBlur: 24,
        outline: false,
        shadow: false,
      },
      canvas: {
        width: 1920,
        height: 400,
        aspectRatio: "custom",
        presetName: "Website Banner",
      },
    },
  },
  {
    id: "cyberpunk",
    name: "Cyberpunk 2099",
    description: "Distorted chromatic aberration, glitch spikes, and high-frequency scanlines.",
    category: "Display & Tech",
    config: {
      ...DEFAULT_CONFIG,
      text: "SYSTEM BREACH DETECTED // PROTOCOL 404 // SYNTHETIC REALITY OVERRIDE",
      direction: "left",
      speed: 180,
      typography: {
        ...DEFAULT_CONFIG.typography,
        fontFamily: "JetBrains Mono",
        fontSize: 58,
        fontWeight: 800,
        letterSpacing: 4,
        textTransform: "uppercase",
      },
      colors: {
        ...DEFAULT_CONFIG.colors,
        textColor: "#facc15",
        colorMode: "solid",
      },
      background: {
        ...DEFAULT_CONFIG.background,
        type: "solid",
        color: "#08090d",
      },
      effects: {
        ...DEFAULT_CONFIG.effects,
        glow: true,
        glowColor: "#eab308",
        glowIntensity: 3,
        glowBlur: 14,
        glitch: true,
        glitchIntensity: 4,
        glitchFrequency: 3,
        glitchOffset: 6,
        rgbSplit: true,
        rgbSplitOffset: 5,
        rgbSplitIntensity: 1,
        scanlines: true,
        scanlinesDensity: 3,
        scanlinesOpacity: 0.35,
        scanlinesSpeed: 2,
      },
      canvas: {
        width: 1920,
        height: 400,
        aspectRatio: "custom",
        presetName: "Website Banner",
      },
    },
  },
  {
    id: "led-display",
    name: "LED Matrix",
    description: "Physical electronic stadium display simulation with amber phosphor dots.",
    category: "Display & Tech",
    config: {
      ...DEFAULT_CONFIG,
      text: "GATE B12 NOW BOARDING — FLIGHT 884 TO TOKYO — ENJOY YOUR FLIGHT",
      direction: "left",
      speed: 140,
      typography: {
        ...DEFAULT_CONFIG.typography,
        fontFamily: "Space Grotesk",
        fontSize: 60,
        fontWeight: 700,
        letterSpacing: 5,
        textTransform: "uppercase",
      },
      colors: {
        ...DEFAULT_CONFIG.colors,
        textColor: "#f59e0b",
        colorMode: "solid",
      },
      background: {
        ...DEFAULT_CONFIG.background,
        type: "pattern",
        color: "#0a0a0c",
        pattern: "dots",
        patternOpacity: 0.4,
        patternScale: 10,
      },
      effects: {
        ...DEFAULT_CONFIG.effects,
        led: true,
        ledDotSize: 3,
        ledDotSpacing: 6,
        ledBrightness: 0.9,
        glow: true,
        glowColor: "#f59e0b",
        glowIntensity: 3,
        glowBlur: 12,
        scanlines: true,
        scanlinesDensity: 4,
        scanlinesOpacity: 0.2,
        scanlinesSpeed: 0,
      },
      canvas: {
        width: 1920,
        height: 400,
        aspectRatio: "custom",
        presetName: "Website Banner",
      },
    },
  },
  {
    id: "stock-ticker",
    name: "Wall Street Ticker",
    description: "Continuous real-time market data stream with green and cyan accents.",
    category: "Broadcast & Retro",
    config: {
      ...DEFAULT_CONFIG,
      text: "▲ NVDA 124.50 (+4.2%)   ▼ AAPL 221.80 (-0.8%)   ▲ MSFT 432.10 (+1.4%)   ▲ TSLA 254.20 (+3.7%)   ▼ GOOGL 178.90 (-0.3%)",
      direction: "left",
      speed: 160,
      typography: {
        ...DEFAULT_CONFIG.typography,
        fontFamily: "JetBrains Mono",
        fontSize: 50,
        fontWeight: 700,
        letterSpacing: 2,
        textTransform: "uppercase",
      },
      colors: {
        ...DEFAULT_CONFIG.colors,
        textColor: "#22c55e",
        colorMode: "solid",
      },
      background: {
        ...DEFAULT_CONFIG.background,
        type: "solid",
        color: "#020817",
      },
      effects: {
        ...DEFAULT_CONFIG.effects,
        glow: true,
        glowColor: "#15803d",
        glowIntensity: 2,
        glowBlur: 10,
        scanlines: false,
      },
      canvas: {
        width: 1920,
        height: 400,
        aspectRatio: "custom",
        presetName: "Website Banner",
      },
    },
  },
  {
    id: "retro-crt",
    name: "Retro CRT",
    description: "Authentic 1980s computer terminal monitor with phosphor persistence.",
    category: "Broadcast & Retro",
    config: {
      ...DEFAULT_CONFIG,
      text: "COMMODORE-64 BASIC V2. 64K RAM SYSTEM. READY. LOAD \"*\",8,1",
      direction: "left",
      speed: 120,
      typography: {
        ...DEFAULT_CONFIG.typography,
        fontFamily: "Fira Code",
        fontSize: 54,
        fontWeight: 500,
        letterSpacing: 3,
        textTransform: "uppercase",
      },
      colors: {
        ...DEFAULT_CONFIG.colors,
        textColor: "#4ade80",
        colorMode: "solid",
      },
      background: {
        ...DEFAULT_CONFIG.background,
        type: "pattern",
        color: "#051608",
        pattern: "scanlines",
        patternOpacity: 0.35,
        patternScale: 6,
      },
      effects: {
        ...DEFAULT_CONFIG.effects,
        glow: true,
        glowColor: "#22c55e",
        glowIntensity: 5,
        glowBlur: 18,
        scanlines: true,
        scanlinesDensity: 4,
        scanlinesOpacity: 0.4,
        scanlinesSpeed: 2,
      },
      canvas: {
        width: 1920,
        height: 400,
        aspectRatio: "custom",
        presetName: "Website Banner",
      },
    },
  },
  {
    id: "terminal",
    name: "Linux Terminal",
    description: "Pure hacker command-line aesthetic in high-density green monospace.",
    category: "Display & Tech",
    config: {
      ...DEFAULT_CONFIG,
      text: "guest@scrollforge:~$ curl -sSL https://get.scrollforge.dev | bash && start-motion",
      direction: "left",
      speed: 140,
      typography: {
        ...DEFAULT_CONFIG.typography,
        fontFamily: "JetBrains Mono",
        fontSize: 48,
        fontWeight: 500,
        letterSpacing: 2,
        textTransform: "none",
      },
      colors: {
        ...DEFAULT_CONFIG.colors,
        textColor: "#10b981",
        colorMode: "solid",
      },
      background: {
        ...DEFAULT_CONFIG.background,
        type: "solid",
        color: "#000000",
      },
      effects: {
        ...DEFAULT_CONFIG.effects,
        glow: false,
        scanlines: false,
      },
      canvas: {
        width: 1920,
        height: 400,
        aspectRatio: "custom",
        presetName: "Website Banner",
      },
    },
  },
  {
    id: "announcement",
    name: "Massive Announcement",
    description: "Monumental high-contrast headline with dynamic diagonal presence.",
    category: "Essential",
    config: {
      ...DEFAULT_CONFIG,
      text: "★ WORLD TOUR 2026 ★ TICKETS ON SALE TODAY ★ SPECIAL GUESTS ANNOUNCED ★",
      direction: "left",
      speed: 200,
      typography: {
        ...DEFAULT_CONFIG.typography,
        fontFamily: "Bebas Neue",
        fontSize: 100,
        fontWeight: 400,
        letterSpacing: 4,
        textTransform: "uppercase",
      },
      colors: {
        ...DEFAULT_CONFIG.colors,
        colorMode: "gradient",
        textColor: "#f97316",
        gradientStart: "#f97316",
        gradientEnd: "#ec4899",
        gradientAngle: 45,
      },
      background: {
        ...DEFAULT_CONFIG.background,
        type: "solid",
        color: "#09090b",
      },
      effects: {
        ...DEFAULT_CONFIG.effects,
        glow: true,
        glowColor: "#f97316",
        glowIntensity: 3,
        glowBlur: 20,
        shadow: true,
        shadowX: 0,
        shadowY: 4,
        shadowBlur: 16,
        shadowSpread: 0,
        shadowColor: "rgba(0,0,0,0.8)",
      },
      canvas: {
        width: 1920,
        height: 400,
        aspectRatio: "custom",
        presetName: "Website Banner",
      },
    },
  },
  {
    id: "vertical-credits",
    name: "Cinema Credits",
    description: "Classic vertical end credits rolling continuously from bottom to top.",
    category: "Broadcast & Retro",
    config: {
      ...DEFAULT_CONFIG,
      text: "SCROLLFORGE STUDIOS\n\nDIRECTED BY\nTHE MOTION LAB\n\nEXECUTIVE PRODUCER\nCHIEF ARCHITECT\n\nLEAD DESIGNER\nSTUDIO ART DIRECTOR\n\nSPECIAL THANKS TO ALL CREATORS",
      direction: "up",
      speed: 70,
      typography: {
        ...DEFAULT_CONFIG.typography,
        fontFamily: "Times New Roman",
        fontSize: 44,
        fontWeight: 400,
        letterSpacing: 4,
        lineHeight: 1.8,
        textTransform: "uppercase",
        textAlign: "center",
      },
      colors: {
        ...DEFAULT_CONFIG.colors,
        textColor: "#f8fafc",
        colorMode: "solid",
      },
      background: {
        ...DEFAULT_CONFIG.background,
        type: "solid",
        color: "#000000",
      },
      effects: {
        ...DEFAULT_CONFIG.effects,
        glow: false,
        shadow: false,
      },
      canvas: {
        width: 1080,
        height: 1080,
        aspectRatio: "1:1",
        presetName: "Square Post (1:1)",
      },
    },
  },
  {
    id: "social-media",
    name: "Story & Reel (9:16)",
    description: "Vertical 9:16 mobile canvas with punchy typography and dynamic gradient.",
    category: "Bold & Neon",
    config: {
      ...DEFAULT_CONFIG,
      text: "NEW DROP IS LIVE • TAP TO SHOP • FREE SHIPPING WORLDWIDE • LIMITED QUANTITIES",
      direction: "left",
      speed: 160,
      typography: {
        ...DEFAULT_CONFIG.typography,
        fontFamily: "Anton",
        fontSize: 68,
        fontWeight: 400,
        letterSpacing: 3,
        textTransform: "uppercase",
      },
      colors: {
        ...DEFAULT_CONFIG.colors,
        colorMode: "gradient",
        textColor: "#ffffff",
        gradientStart: "#38bdf8",
        gradientEnd: "#818cf8",
        gradientAngle: 90,
      },
      background: {
        ...DEFAULT_CONFIG.background,
        type: "gradient",
        color: "#0f172a",
        gradientStart: "#1e1b4b",
        gradientEnd: "#020617",
        gradientAngle: 180,
        gradientType: "linear",
      },
      effects: {
        ...DEFAULT_CONFIG.effects,
        glow: true,
        glowColor: "#38bdf8",
        glowIntensity: 3,
        glowBlur: 16,
        outline: false,
      },
      canvas: {
        width: 1080,
        height: 1920,
        aspectRatio: "9:16",
        presetName: "Story / Reel (9:16)",
      },
    },
  },
  {
    id: "website-banner",
    name: "Editorial Banner",
    description: "High-density horizontal ribbon built for headers, promotions, and shop banners.",
    category: "Essential",
    config: {
      ...DEFAULT_CONFIG,
      text: "FREE WORLDWIDE SHIPPING ON ORDERS OVER $75 • 30-DAY MONEY-BACK GUARANTEE • 24/7 CUSTOMER SUPPORT",
      direction: "left",
      speed: 120,
      typography: {
        ...DEFAULT_CONFIG.typography,
        fontFamily: "Inter",
        fontSize: 42,
        fontWeight: 700,
        letterSpacing: 2,
        textTransform: "uppercase",
      },
      colors: {
        ...DEFAULT_CONFIG.colors,
        textColor: "#090a0f",
        colorMode: "solid",
      },
      background: {
        ...DEFAULT_CONFIG.background,
        type: "solid",
        color: "#fbbf24", // Vibrant amber banner
      },
      effects: {
        ...DEFAULT_CONFIG.effects,
        glow: false,
        shadow: false,
      },
      canvas: {
        width: 1920,
        height: 400,
        aspectRatio: "custom",
        presetName: "Website Banner",
      },
    },
  },
];
